name: on-schedule
run-name: on schedule

on:
  schedule:
    # weekly
    - cron: "0 0 * * 1"

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-preview:
    uses: ./.github/workflows/build-preview.yaml
